In [ ]:
import matplotlib.pyplot as plt
import geopandas as gpd
import geodatasets
import pandas as pd

geodatasets.data.flatten().keys()
geodatasets.data.query_name("geoda airbnb")
geodatasets.data

In [ ]:
# Step 1: Load the dataset using the new geodatasets package
path = geodatasets.get_path("naturalearth.land")

world = gpd.read_file(path)

print("GeoDataFrame columns:", world.columns)

url = "https://naciscdn.org"
world = gpd.read_file(url)
print("GeoDataFrame columns:", world.columns)

custom_data = pd.DataFrame(
    {
        "Country_Name": [
            "United States of America",
            "Canada",
            "Brazil",
            "China",
            "India",
            "Australia",
            "France",
        ],
        "Your_Metric": [850, 620, 450, 920, 880, 310, 540],
    }
)
# Step 2: Initialize the Matplotlib figure and axis
fig, ax = plt.subplots(1, 1, figsize=(15, 10))

# Step 3: Plot the map
world.plot(
    cmap="OrRd",  # The Matplotlib colormap
    edgecolor="black",  # Border color
    linewidth=0.5,  # Border line width
    ax=ax,  # Plot on the established Matplotlib axis
)
# Step 4: Customize the layout and show the plot
ax.set_title("Global Landmass Map", fontsize=16)
# ax.set_axis_off()  # Hide latitude/longitude grid lines

plt.show()

In [ ]:
population_df = pd.read_csv("../../data/population.csv")
population_df.rename(columns={"Population 2024": "Population"}, inplace=True)
world.head()

In [ ]:
url = "https://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_countries.zip"
world = gpd.read_file(url)
with pd.option_context("display.max_columns", None):
    print(world.columns)

In [ ]:
import pandas as pd
import plotly.express as px

# 1. आपका डेटा (यदि आपके पास CSV फ़ाइल है, तो इस लाइन को अनकमेंट करें:)
# df = pd.read_csv("your_file.csv")

# सैंपल डेटा जो आपके कॉलम्स से मैच करता है:
data = {
    "Country": [
        "United States",
        "China",
        "Japan",
        "Germany",
        "India",
        "United Kingdom",
        "France",
        "Brazil",
        "Canada",
        "Australia",
    ],
    "Population": [
        333287557,
        1412600000,
        1251240000,
        84080000,
        1417173173,
        67330000,
        67970000,
        215300000,
        38930000,
        26010000,
    ],
    "Per_Capita_Income_USD": [
        76399,
        12720,
        33815,
        48432,
        2389,
        45850,
        40960,
        8917,
        54966,
        64491,
    ],
    "Economy_GDP_USD_Trillion": [
        25.46,
        17.96,
        4.23,
        4.07,
        3.39,
        3.07,
        2.78,
        1.92,
        2.14,
        1.68,
    ],
}

df = pd.DataFrame(data)

# 2. इंटरैक्टिव Choropleth मैप बनाना
# हम यहाँ 'Per_Capita_Income_USD' के आधार पर मैप को कलर कर रहे हैं
fig = px.choropleth(
    df,
    locations="Country",  # वह कॉलम जिसमें देशों के नाम हैं
    locationmode="country names",  # Plotly को बताना कि नाम के ज़रिए मैप करना है
    color="Per_Capita_Income_USD",  # इस वैल्यू के आधार पर नक्शे का रंग बदलेगा
    hover_name="Country",  # टूलटिप के सबसे ऊपर देश का नाम दिखेगा
    # टूलटिप (Hover Window) में बाकी सारे कॉलम्स का डेटा फॉर्मेट के साथ जोड़ना
    hover_data={
        "Per_Capita_Income_USD": ":$,.0f",  # डॉलर सिंबल और कॉमा फॉर्मेट ($76,399)
        "Economy_GDP_USD_Trillion": ":$.2f T",  # GDP को ट्रिलियन फॉर्मेट ($25.46 T)
        "Population": ":,.0f",  # पापुलेशन में कॉमा सेपेरेटर (1,417,173,173)
        "Country": False,  # दोबारा नाम दिखने से रोकने के लिए False
    },
    color_continuous_scale="Viridis",  # रंग बदलने की सुंदर पैलेट (जैसे: Viridis, Plasma, Cividis)
    labels={
        "Per_Capita_Income_USD": "Per Capita Income (USD)",
        "Economy_GDP_USD_Trillion": "GDP (Trillion USD)",
        "Population": "Total Population",
    },
    title="<b>Global Interactive Map: Economic & Population Overview</b>",
)

# 3. मैप के लेआउट और विज़ुअल्स को बेहतर बनाना
fig.update_layout(
    title_font_size=20,
    title_x=0.5,  # टाइटल को बीच में (Center) करने के लिए
    margin={"r": 0, "t": 60, "l": 0, "b": 0},  # मार्जिन कम करके मैप को बड़ा फ्रेम देना
    geo=dict(
        showframe=False,
        showcoastlines=True,
        projection_type="equirectangular",  # इसे "orthographic" करके आप 3D Globe भी बना सकते हैं
    ),
)

# मैप को ब्राउज़र या जुपिटर नोटबुक में दिखाएं
fig.show()

In [42]:
df = pd.read_csv("../../data/world_country_data.csv")
df["Country"]
routs_data = {
    "Origin_Country": [df.iat[0, 0]] * (len(df) - 1),
    "Origin_Lat": [df.iat[0, 4]] * (len(df) - 1),
    "Origin_Lon": [df.iat[0, 5]] * (len(df) - 1),
    "Dest_Country": df.loc[df["Country"] != "United States", "Country"],
    "Dest_Lat": df.loc[df["Country"] != "United States", "Latitude"],
    "Dest_Lon": df.loc[df["Country"] != "United States", "Longitude"],
    "Population": df.loc[df["Country"] != "United States", "Population"],
    "Per_Capita_Income_USD": df.loc[
        df["Country"] != "United States", "Per_Capita_Income_USD"
    ],
    "Economy_GDP_USD_Trillion": df.loc[
        df["Country"] != "United States", "Economy_GDP_USD_Trillion"
    ],
}
f'{len(routs_data["Origin_Country"])}->{len(routs_data["Origin_Lat"])}->{len(routs_data["Origin_Lon"])}->{len(routs_data["Dest_Country"])}->{len(routs_data["Dest_Lat"])}->{len(routs_data["Dest_Lon"])}->{len(routs_data["Population"])}->{len(routs_data["Per_Capita_Income_USD"])}->{len(routs_data["Economy_GDP_USD_Trillion"])}'
# df.size

# countries_series = df.loc[df["Country"] != "United States", "Economy_GDP_USD_Trillion"]
# countries_series

'24->24->24->24->24->24->24->24->24'

In [ ]:
import pandas as pd
import plotly.graph_objects as go

# 1. देशों का डेटा (Geographic Coordinates के साथ)
# यहाँ हमने रूट्स डिफाइन किए हैं (जैसे USA से भारत, चीन, ब्राजील आदि)
routes_data = {
    "Origin_Country": [
        "United States",
        "United States",
        "United States",
        "United States",
        "United States",
    ],
    "Origin_Lat": [37.0902, 37.0902, 37.0902, 37.0902, 37.0902],
    "Origin_Lon": [-95.7129, -95.7129, -95.7129, -95.7129, -95.7129],
    "Dest_Country": ["India", "China", "Brazil", "United Kingdom", "Australia"],
    "Dest_Lat": [20.5937, 35.8617, -14.2350, 55.3781, -25.2744],
    "Dest_Lon": [78.9629, 104.1954, -51.9253, -3.4360, 133.7751],
    # आपका पिछला आर्थिक डेटा (मंजिल वाले देश का)
    "Population": [78.9629, 104.1954, -51.9253, -3.4360, 133.7751],
    "Per_Capita_Income_USD": [78.9629, 104.1954, -51.9253, -3.4360, 133.7751],
    "Economy_GDP_USD_Trillion": [3.39, 17.96, 1.92, 3.07, 1.68],
}

df = pd.DataFrame(routes_data)

# 2. खाली मैप बेस (Empty Map Figure) की शुरुआत करें
fig = go.Figure()

# 3. मैप पर कनेक्शन लाइन्स (Lines) जोड़ना
for i in range(len(df)):
    fig.add_trace(
        go.Scattergeo(
            locationmode="country names",
            lon=[df["Origin_Lon"][i], df["Dest_Lon"][i]],
            lat=[df["Origin_Lat"][i], df["Dest_Lat"][i]],
            mode="lines",
            line=dict(width=2, color="red"),
            opacity=0.6,
            hoverinfo="skip",  # लाइनों पर माउस ले जाने पर टूलटिप न दिखे
        )
    )

# 4. मंजिल वाले देशों पर इंटरैक्टिव डॉट्स (Markers) जोड़ना
fig.add_trace(
    go.Scattergeo(
        locationmode="country names",
        lon=df["Dest_Lon"],
        lat=df["Dest_Lat"],
        hovertext=df["Dest_Country"],
        mode="markers",
        marker=dict(
            size=10, color="blue", line=dict(width=1, color="rgba(102, 102, 102)")
        ),
        # टूलटिप में दिखने वाली कस्टम जानकारी (Hover Text)
        customdata=df[
            ["Population", "Per_Capita_Income_USD", "Economy_GDP_USD_Trillion"]
        ],
        hovertemplate=(
            "<b>%{hovertext}</b><br><br>"
            + "Population: %{customdata[0]:,.0f}<br>"
            + "Per Capita Income: $%{customdata[1]:,.0f}<br>"
            + "GDP: $%{customdata[2]:.2f} T<br>"
            + "<extra></extra>"  # डिफ़ॉल्ट ट्रेस टेक्स्ट को हटाने के लिए
        ),
    )
)

# 5. मैप का लेआउट सेट करना
fig.update_layout(
    title_text="<b>Global Interactive Connection Map with Economic Data</b>",
    title_x=0.5,
    showlegend=False,
    geo=dict(
        scope="world",
        projection_type="equirectangular",
        showland=True,
        landcolor="rgb(243, 243, 243)",
        countrycolor="rgb(204, 204, 204)",
    ),
    margin={"r": 0, "t": 50, "l": 0, "b": 0},
)

# मैप को ब्राउज़र या जुपिटर नोटबुक में दिखाएं
# fig.show()

In [ ]:
import numpy as np

# 1. Generate data grid
x = np.linspace(-5, 5, 100)
x

In [7]:
y = np.linspace(-5, 5, 100)
X, Y = np.meshgrid(x, y)
Z = np.sin(np.sqrt(X**2 + Y**2))  # The math function defining the surface

print(f"X ->{type(X)}\n", X)
print(f"Y ->{type(Y)}\n", Y)
print(f"Z ->{type(Z)}\n", Z)

X -><class 'numpy.ndarray'>
 [[-5.        -4.8989899 -4.7979798 ...  4.7979798  4.8989899  5.       ]
 [-5.        -4.8989899 -4.7979798 ...  4.7979798  4.8989899  5.       ]
 [-5.        -4.8989899 -4.7979798 ...  4.7979798  4.8989899  5.       ]
 ...
 [-5.        -4.8989899 -4.7979798 ...  4.7979798  4.8989899  5.       ]
 [-5.        -4.8989899 -4.7979798 ...  4.7979798  4.8989899  5.       ]
 [-5.        -4.8989899 -4.7979798 ...  4.7979798  4.8989899  5.       ]]
Y -><class 'numpy.ndarray'>
 [[-5.        -5.        -5.        ... -5.        -5.        -5.       ]
 [-4.8989899 -4.8989899 -4.8989899 ... -4.8989899 -4.8989899 -4.8989899]
 [-4.7979798 -4.7979798 -4.7979798 ... -4.7979798 -4.7979798 -4.7979798]
 ...
 [ 4.7979798  4.7979798  4.7979798 ...  4.7979798  4.7979798  4.7979798]
 [ 4.8989899  4.8989899  4.8989899 ...  4.8989899  4.8989899  4.8989899]
 [ 5.         5.         5.        ...  5.         5.         5.       ]]
Z -><class 'numpy.ndarray'>
 [[0.70886129 0.65699209 0